/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as cars from "../cars.js";
import type * as files from "../files.js";
import type * as http from "../http.js";
import type * as listAuctions from "../listAuctions.js";
import type * as manufacturer from "../manufacturer.js";
import type * as parts from "../parts.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  cars: typeof cars;
  files: typeof files;
  http: typeof http;
  listAuctions: typeof listAuctions;
  manufacturer: typeof manufacturer;
  parts: typeof parts;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
